app = "digital-graveyard-ermizamr"
primary_region = "ewr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[mounts]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
